### ISSUE TITLE
Update Button joined component

### ISSUE THREAD

**Issue by bluemoonecho** [bitcrowd/bitstyles_phoenix#112] opened 2023-06-27 13:02 UTC
Update button joined component to follow the new designs. 

https://bitcrowd.github.io/bitstyles/?path=/docs/ui-buttons-joined--plus-minus-icons-outline

**Comment by andreasknoepfle** [comment] 2023-07-20 10:20
Duplicate of #51

**Closed** 2023-07-20 10:20 UTC
